{% set name = "prokaregia" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/schmigle/prokaregia/archive/v{{ version }}.tar.gz
  sha256: PLACEHOLDER_SHA256_HASH  # Replace with actual hash after creating GitHub release

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('prokaregia', max_pin="x") }}

requirements:
  run:
    - python >=3.12
    - snakemake-minimal =8.11.0  

test:
  commands:
    - prokaregia -h

about:
  home: https://github.com/schmigle/prokaregia
  license: MIT
  license_file: LICENSE
  summary: 'Automated long-read assembly and binning pipeline for prokaryotic genomes'
  description: |
    ProkaRegia is a Snakemake-based pipeline for processing long-read
    sequencing data (ONT/PacBio) to assemble and bin prokaryotic genomes.
    It includes quality control, assembly, polishing, binning, and quality assessment.
  doc_url: https://github.com/schmigle/prokaregia
  dev_url: https://github.com/schmigle/prokaregia

extra:
  recipe-maintainers:
    - schmigle
